"""
Django settings for proyecto_pedidos project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

# Importar Path de pathlib para manejar rutas de archivos de manera moderna
from pathlib import Path

# Construir rutas dentro del proyecto de esta manera: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Configuraciones rápidas de desarrollo - no aptas para producción
# Ver https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# ADVERTENCIA DE SEGURIDAD: mantener la clave secreta usada en producción secreta!
SECRET_KEY = 'django-insecure-#1nry-o!6np%0bd!fo6k49d3!iei14l*s$hn(3r#5j*wk-64e5'

# ADVERTENCIA DE SEGURIDAD: no ejecutar con debug activado en producción!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

# Lista de aplicaciones instaladas en el proyecto
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pedidos'  # Nuestra aplicación personalizada
]

# Middleware utilizado en el proyecto
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'proyecto_pedidos.urls'  # Configuración de URLs raíz del proyecto

# Configuración de plantillas
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',  # Backend de plantillas de Django
        'DIRS': [],  # Directorios adicionales para buscar plantillas (vacío para usar solo APP_DIRS)
        'APP_DIRS': True,  # Buscar plantillas en directorios de apps
        'OPTIONS': {
            'context_processors': [  # Procesadores de contexto para agregar variables globales
                'django.template.context_processors.debug',  # Para debug en plantillas
                'django.template.context_processors.request',  # Para acceder al request en plantillas
                'django.contrib.auth.context_processors.auth',  # Para autenticación
                'django.contrib.messages.context_processors.messages',  # Para mensajes
            ],
        },
    },
]

WSGI_APPLICATION = 'proyecto_pedidos.wsgi.application'  # Aplicación WSGI para el servidor web


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# Configuración de la base de datos (usando MySQL)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'crud_pedidos',
        'USER': 'root',
        'PASSWORD': '',  # Cambia a '' si no hay contraseña en XAMPP
        'HOST': 'localhost',
        'PORT': '3306',
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

# Validadores de contraseñas
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internacionalización
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'  # Código de idioma (inglés de EE.UU.)

TIME_ZONE = 'UTC'  # Zona horaria (Tiempo Universal Coordinado)

USE_I18N = True  # Usar internacionalización (traducciones)

USE_TZ = True  # Usar zonas horarias


# Archivos estáticos (CSS, JavaScript, Imágenes)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'  # URL base para archivos estáticos

# Tipo de campo de clave primaria por defecto
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'  # Campo auto de tipo BigAutoField
