# Generated by Django 4.1 on 2025-12-14 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pedido',
            table='pedidos',
        ),
    ]
